apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controlmyspa-porssari
  labels:
    app: controlmyspa-porssari
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: poreallas.aukia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: controlmyspa-porssari
                port:
                  number: 8080
  tls:
    - hosts:
        - poreallas.aukia.com
      secretName: poreallas-aukia-com-tls
