apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controlmyspa-porssari-data
  labels:
    app: controlmyspa-porssari
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
