apiVersion: v1
kind: Secret
metadata:
    name: controlmyspa-porssari
    labels:
        app: controlmyspa-porssari
type: Opaque
stringData:
    CONTROLMYSPA_USER: ENC[AES256_GCM,data:J+i/S0t+YT5zc7M=,iv:OfBczwpFAO/3YP9awN9ILa9gIXnyWE1bUuclHZuFIzk=,tag:qfSR8JghDyMLtA6QpYqwrA==,type:str]
    CONTROLMYSPA_PASS: ENC[AES256_GCM,data:9Y7SaHsE4H14mvHkEQ==,iv:RgZfM7luV7sWgwUWnARWQ5Yj95ZrCPkjHF7FCS2aqKA=,tag:hiCQfYPLuMV1p8RDtgB37A==,type:str]
    PORSSARI_MAC: ENC[AES256_GCM,data:tKkksEGzLIpGVcH4,iv:I4iw1DaZE6sO0zqDBNEKZo249QPA8ljUmgnx1Gfvjz8=,tag:Nk7Xx+io40rMZMpk3Qm5zA==,type:str]
    SENTRY_URL: ENC[AES256_GCM,data:kZLVVuCHZGM9KWWswfr1UHi8DAAtYkaKVf5AHd3J1kYzhfjjZRUF+3gsXOaWIGML4P/rKAOxzhhYvHd3Xd/jqd73UXAay9sD3L5xbu1lStpkpQ==,iv:hUPDURCu+k6uqdd8DQpb4K6H86CD+C4moCppTmhFjwg=,tag:MchSupvnJXQIxXwzyXMULw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:fQVTbS0V6D0PZsH4/PcodktMuCSyFTVuNnFy/uLpKQzbvF0f1kdXXzLgHvIByw==,iv:drwR28TgdQJNWUW2YkQb2nEx4GEd0EddRTkB8WSTz78=,tag:HYuViFXNU5Wy3qCYKV8CZw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:jJnaBAKiTHDGIg==,iv:OYx3jGZnu4cvEmtlGLkZU1NfPKZ13Y3npZ+RYQKsNJg=,tag:ncHLA/ZUWiWE/Dd4BGYJzg==,type:str]
sops:
    age:
        - recipient: age1ff6tzagxcpskm2p2jnu2kulfg47cqh5g60hfc5w3hv6r32cy3fqqgcyjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM25UZXd2WFlqdG12REtV
            NWtVbmlyRGNicTc2clVxTmJHbWxmLzhJL0I4ClFXeXQ5ZkM4ZURYUHlZQmhZcDlC
            RkR0Nnl2WTVRM3BtSG9VYXFFS21qZ2MKLS0tIHhueXBaeHZRNDZuVUFlc21Zd1dH
            SmVQMmMwWXBnVC81QUI1VGVIejF3aFkKtVnE3LeehWCWOpe1sxQeMS5v3lpA8l0T
            6E2fE8a6IC1FqDgEwWJWwue6sGrTC8usq37mzHhFHWEAzqNDHQnDiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:26:25Z"
    mac: ENC[AES256_GCM,data:cof3uF37w+/cMCU1xpD6t6OSDJir5WBgYj0BjtDwY8pzFB9rTtZjuf90oXSIdA71r2C94BApW3u01BWWbLi1Fo/GTt26XNTIeVcE74Lrj2kICHQT3O7cbMF+gAYU85bh88TKZXxAs01NOEHfRPRvV3JjycaQkmhSk4tU7q6Qz5Y=,iv:GhL511Xw5Hu1XZU9nuRb3uaS9QORlECXRNyChsSQQM4=,tag:vfU48gj13JPyrK05M202pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
