apiVersion: v1
kind: Secret
metadata:
    name: controlmyspa-porssari
    labels:
        app: controlmyspa-porssari
type: Opaque
stringData:
    CONTROLMYSPA_USER: ENC[AES256_GCM,data:GfwulxZdvX+CaWg=,iv:EM8cAeGMM+jQDhm435xqQxipghY9RXMcJWpwaLQdEEM=,tag:WBtTphZSaC2UGlrWhIUR8w==,type:str]
    CONTROLMYSPA_PASS: ENC[AES256_GCM,data:6S6YQfBpPoZEFuv8Cw==,iv:1SA3pTuGrr/p1h0Bvz+AaboA+p5D9Tmem33tm8ShKB8=,tag:MDwwxPgXzzDW0rPfrWMmHA==,type:str]
    PORSSARI_MAC: ENC[AES256_GCM,data:q6D/AcOs6OtuFdNe,iv:Sifw9+xzs5Ya1Oalt7dnIlayamhzPX1bzcHaTuKZRJ4=,tag:SGC/0QI70ROZva3H+i9N5w==,type:str]
    SENTRY_URL: ENC[AES256_GCM,data:psODmLKpwJG+wgksBK/zlEL+PDy3kfNxQFPqnCXqwLEiE68AwSZukl1FuiTLEdGDwg+jbqMPlg73hEGIOOR/99qrVSAV3v/go3jko3uJ+eOy8A==,iv:pkQMcUYDDC6yaCtYSpcrnWh92gFKfb30TiLPl45QwcY=,tag:zQsyQ17zCz6mOj8wnlEVAA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:+c0utru7NX0TDHN/UnJv877BFhPetMpT+yY89wbIpsmI21dgby+6N7r/kozXEw==,iv:kPDVWYO89Vyl76tnlQ/0/AXs8f8cop0K1m/7+EqGeD0=,tag:1ykXxBFH1NNDSrXQT6NW9A==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:BH9j79F0HWnWdg==,iv:jIFw6C4n4Cdp8x+nAdOpeQD/DI8yrpjXAWgvsgc/tSk=,tag:2NT+CiQmvoxS1DBg7QvP0w==,type:str]
    TELEGRAM_WEBHOOK_URL: ENC[AES256_GCM,data:fVxV8hyplZoYH7ZrB/jhfuZoaRtNajPPN+9w,iv:SJjZKgAVJjygGFwzMnflL/30dD3Jko8y+3ODyp9C0Zo=,tag:pLEDGo4jdlQpjxiBm1Lnpg==,type:str]
sops:
    age:
        - recipient: age1ff6tzagxcpskm2p2jnu2kulfg47cqh5g60hfc5w3hv6r32cy3fqqgcyjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSUV1SUZoVUU2YXZia2FR
            bys5V01nT2ZDSGFjeXRpa0ErSkg0VEVqU2pjCk5TcVE1NVNkM1JVbml5dThqUkJ6
            N1A0eVZWZW9SZ3pkRFBDQ0xpdDFxQWcKLS0tIHc1dlNodW4wSFpnOFZyaWRhZlN3
            OUhHV2JlaVJxcmpzYTQvM3ZhSVhSYU0KAXTA885lOK7WpincDp4hm+CFdlpZQggu
            ggn6vWMnbIqRdUuST63FcUjP1TjHL5iTt78CFC9DUDC1BDs+/OZVfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:43:07Z"
    mac: ENC[AES256_GCM,data:QfIMFDaebhD79p4Jzk4iclNwW4aQMbdVRQuSMF5aTzdPp+uj+FihDuLpf3A1Pu01c9XG28mFRSfZ7mlDkfxYD7eI6hWKUht47MCute2OjIGzaKKXOj0Xz191IU8sxGYo+RkzL1PUU2YNdAMkGhsp6tGL2fCdoTBq1AztZ/K93DY=,iv:BVewQehFP3sAX9v9+tFPqdzFwt/rfcC7XgLvgOZLwRo=,tag:UA3KJTS1WqU5hCHvbDuKTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
