apiVersion: v1
kind: Secret
metadata:
    name: controlmyspa-porssari
    labels:
        app: controlmyspa-porssari
type: Opaque
stringData:
    CONTROLMYSPA_USER: ENC[AES256_GCM,data:3IeAu2Yn24GsQ4g=,iv:/0hjdQhcM6BPunASPMoSM9i4hJ1ARaCE5eLzDod9GfU=,tag:9oMHBAX6McbZaop+rVQmew==,type:str]
    CONTROLMYSPA_PASS: ENC[AES256_GCM,data:0j8xr665naEGT+K0gA==,iv:Y/Dt1JQk8xDLbFCC3lfX7kyeDguZw/m1Vm77/jr/e40=,tag:tS/P+xAAOowEkSsiwva2lg==,type:str]
    PORSSARI_MAC: ENC[AES256_GCM,data:ja4s3NOxCX/qh7B0,iv:/merr30WTWx4EGvET4lUEEqh/+KCLGAKk25k8jdm6Rg=,tag:lK4wgtzqENMbgEhBVm8Hdg==,type:str]
    SENTRY_URL: ENC[AES256_GCM,data:Sob7TZyveygfq5hB4YI18zAbtD8V6HtFdhw/eS7VDEW1XckcnTsSp1GbmxSzG1AlaPNxhy9Xcv6b9OLyVN5o+WT+PiKE9EgRIQUXu1Ep2dUyLA==,iv:kINKqFCArOxUJe53jgMuWM0k1LfY0I69Ac7J2S4KVWo=,tag:X45X2K2ebvfBYy+v9iAIHQ==,type:str]
sops:
    age:
        - recipient: age1ff6tzagxcpskm2p2jnu2kulfg47cqh5g60hfc5w3hv6r32cy3fqqgcyjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUFNmbUdraDRCWUo0VVdW
            REx2MlRzVUJzZkRaR0hKWFRtRDdKQTJtVENRClAweGw4OVJ3SnNNUTlySFhxUjJu
            M05QYm10NXMrL3hKTlRJUkwrQlc4VXcKLS0tIDRjcktDakpXcTEyUEJVcHNlMmo0
            bGY4MmZTZ29vZExndVNlMFRnS2d0ODQK/CV/Ft18FzPkbl3FCEmdDiL4j4wu12lO
            kJTQZo/IODit/B3NPBLTfYgMIn4n7Tnht9O5eekiFtNHXSSAXoETlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T08:47:46Z"
    mac: ENC[AES256_GCM,data:/RBEy5AH76P9prGnyApkXpGHxh74bt0lkvyyZNVb2HJ/y515ADWhyObCs/LKyxONoSG4wxXnyy7sGlTdAVZ4pQRXF2iPBAt2RsS0Z168ydKMOGBJPtSHj3inJF6gUwb8CYOGFtegc076QovzogEkLwrnKUN3g7C5QORupl6xbGU=,iv:id8kpcm7z3SesaXUdAP+hq60bjN4fWDCbRXaQCHRIWk=,tag:M0DMvDWuAhpvYkahnRHdtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
