apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
          resources:
            limits:
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 2
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: mosquitto
