apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-postgres-data
  labels:
    app: teslamate-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
